import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { Employee, EmployerSettings } from "./schema";
import { format } from "date-fns";
import { getNMWForDate } from "./legal/registry";

const AMBER = rgb(0.77, 0.48, 0.11);
const DARK = rgb(0.11, 0.09, 0.08);
const SLATE = rgb(0.45, 0.40, 0.35);
const WHITE = rgb(1, 1, 1);
const LINE = rgb(0.88, 0.86, 0.83);
const BG_SECTION = rgb(0.97, 0.96, 0.95);

export async function generateEmploymentContract(
    employee: Employee,
    settings: EmployerSettings
): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_W = 595.28;
    const PAGE_H = 841.89;
    const MARGIN = 50;
    const BODY_W = PAGE_W - MARGIN * 2;

    const startDate = employee.startDate ? new Date(employee.startDate) : new Date();
    const nmw = getNMWForDate(startDate);
    const effectiveDate = format(startDate, "d MMMM yyyy");
    const todayStr = format(new Date(), "d MMMM yyyy");

    // Helper: add a new page
    const addPage = () => {
        const p = pdfDoc.addPage([PAGE_W, PAGE_H]);
        // Footer on every page
        p.drawText("Generated by LekkerLedger · BCEA Compliant · www.lekkerledger.co.za", {
            x: PAGE_W / 2 - regular.widthOfTextAtSize("Generated by LekkerLedger · BCEA Compliant · www.lekkerledger.co.za", 7) / 2,
            y: 25,
            size: 7,
            font: regular,
            color: SLATE,
        });
        p.drawLine({ start: { x: MARGIN, y: 38 }, end: { x: PAGE_W - MARGIN, y: 38 }, thickness: 0.5, color: LINE });
        return p;
    };

    // ── PAGE 1: Header + Parties ──────────────────────────────────────────────
    const p1 = addPage();

    // Dark header band
    p1.drawRectangle({ x: 0, y: PAGE_H - 130, width: PAGE_W, height: 130, color: DARK });
    p1.drawRectangle({ x: 0, y: PAGE_H - 134, width: PAGE_W, height: 4, color: AMBER });

    p1.drawText("EMPLOYMENT CONTRACT", {
        x: PAGE_W / 2 - bold.widthOfTextAtSize("EMPLOYMENT CONTRACT", 22) / 2,
        y: PAGE_H - 62,
        size: 22, font: bold, color: WHITE,
    });
    p1.drawText("Domestic Worker Agreement · Basic Conditions of Employment Act, 1997", {
        x: PAGE_W / 2 - regular.widthOfTextAtSize("Domestic Worker Agreement · Basic Conditions of Employment Act, 1997", 10) / 2,
        y: PAGE_H - 85,
        size: 10, font: regular, color: rgb(0.6, 0.55, 0.5),
    });
    p1.drawText(`Effective Date: ${effectiveDate}   |   Generated: ${todayStr}`, {
        x: PAGE_W / 2 - regular.widthOfTextAtSize(`Effective Date: ${effectiveDate}   |   Generated: ${todayStr}`, 8) / 2,
        y: PAGE_H - 112,
        size: 8, font: regular, color: rgb(0.5, 0.45, 0.4),
    });

    let cy = PAGE_H - 160;

    const section = (page: ReturnType<typeof addPage>, title: string, y: number) => {
        page.drawRectangle({ x: MARGIN, y: y - 6, width: BODY_W, height: 20, color: BG_SECTION });
        page.drawRectangle({ x: MARGIN, y: y + 14, width: 3, height: 20, color: AMBER });
        page.drawText(title, { x: MARGIN + 10, y: y + 4, size: 10, font: bold, color: DARK });
    };

    const row = (page: ReturnType<typeof addPage>, label: string, value: string, y: number) => {
        page.drawText(label + ":", { x: MARGIN + 8, y, size: 9, font: bold, color: SLATE });
        page.drawText(value || "(Not provided)", { x: MARGIN + 160, y, size: 9, font: regular, color: DARK });
    };

    // Preamble
    p1.drawText("This agreement is entered into between the Employer and the Employee named below,", {
        x: MARGIN, y: cy, size: 9, font: regular, color: SLATE, maxWidth: BODY_W,
    });
    cy -= 16;
    p1.drawText("in accordance with the Basic Conditions of Employment Act No. 75 of 1997 (BCEA) and the", {
        x: MARGIN, y: cy, size: 9, font: regular, color: SLATE, maxWidth: BODY_W,
    });
    cy -= 16;
    p1.drawText("Sectoral Determination 7 (Domestic Worker Sector, South Africa).", {
        x: MARGIN, y: cy, size: 9, font: regular, color: SLATE, maxWidth: BODY_W,
    });
    cy -= 30;

    // Section 1: Employer
    section(p1, "1. EMPLOYER DETAILS", cy);
    cy -= 30;
    row(p1, "Name / Business", settings.employerName || "(Not set)", cy); cy -= 18;
    row(p1, "Address", settings.employerAddress || "(Not set)", cy); cy -= 18;
    row(p1, "UIF Reference Number", settings.uifRefNumber || "(Not set)", cy); cy -= 18;

    cy -= 20;

    // Section 2: Employee
    section(p1, "2. EMPLOYEE DETAILS", cy);
    cy -= 30;
    row(p1, "Full Name", employee.name, cy); cy -= 18;
    row(p1, "SA ID / Passport", employee.idNumber || "(Not provided)", cy); cy -= 18;
    row(p1, "Phone Number", employee.phone || "(Not provided)", cy); cy -= 18;
    row(p1, "Job Title / Role", employee.role, cy); cy -= 18;
    row(p1, "Start Date", effectiveDate, cy); cy -= 18;

    cy -= 20;

    // Section 3: Remuneration
    section(p1, "3. REMUNERATION", cy);
    cy -= 30;
    row(p1, "Hourly Rate", `R ${employee.hourlyRate.toFixed(2)} per hour`, cy); cy -= 18;
    row(p1, "National Min. Wage (NMW)", `R ${nmw.toFixed(2)} per hour (SD7 current)`, cy); cy -= 18;
    row(p1, "Pay Frequency", employee.frequency || "Monthly", cy); cy -= 18;
    const uifNote = "1% employee contribution deducted from gross earnings where applicable (BCEA S.86).";
    p1.drawText(uifNote, { x: MARGIN + 8, y: cy, size: 8, font: regular, color: SLATE, maxWidth: BODY_W - 10 });
    cy -= 18;

    cy -= 20;

    // Section 4: Working Hours
    section(p1, "4. WORKING HOURS", cy);
    cy -= 30;
    const hoursPerDay = employee.ordinaryHoursPerDay || 8;
    row(p1, "Ordinary Hours/Day", `${hoursPerDay} hours`, cy); cy -= 18;
    row(p1, "Ordinary Hours/Week", `${hoursPerDay * 5} hours (Mon–Sat, max 45/week per BCEA S.9)`, cy); cy -= 18;
    row(p1, "Works Sundays Ordinarily", employee.ordinarilyWorksSundays ? "Yes (1.5× rate applies)" : "No (2× rate applies if required)", cy); cy -= 18;
    row(p1, "Overtime Rate", "1.5× ordinary for hours > 45/week (BCEA S.10)", cy); cy -= 18;
    row(p1, "Sunday / PH Rate", "2.0× ordinary (SD7 S.6–7)", cy); cy -= 18;

    // ── PAGE 2: Leave + Deductions + Clauses ─────────────────────────────────
    const p2 = addPage();
    cy = PAGE_H - 70;

    // Section 5: Leave
    section(p2, "5. LEAVE ENTITLEMENTS (BCEA S.20–30)", cy);
    cy -= 30;
    const leaveRows = [
        ["Annual Leave", "3 weeks (15 working days) per 12-month cycle (BCEA S.20)."],
        ["Sick Leave", "1 day per 26 days worked (1st 6 months). Then: days normally worked in 6 weeks per 36 months."],
        ["Family Responsibility", "5 days per year (employed > 4 months & ≥ 4 days/week — BCEA S.27)."],
        ["Maternity Leave", "4 consecutive months (unpaid — claimable via UIF — BCEA S.25)."],
        ["Public Holidays", "All workers entitled to public holidays on full pay (BCEA S.18)."],
    ];
    for (const [label, value] of leaveRows) {
        p2.drawText(`${label}:`, { x: MARGIN + 8, y: cy, size: 9, font: bold, color: SLATE });
        p2.drawText(value, { x: MARGIN + 170, y: cy, size: 9, font: regular, color: DARK, maxWidth: BODY_W - 170 });
        cy -= 22;
    }

    cy -= 10;

    // Section 6: Deductions
    section(p2, "6. DEDUCTIONS (SD7 S.19)", cy);
    cy -= 30;
    const dedRows = [
        ["UIF", "1% of gross (up to monthly cap) — BCEA S.86 & UIF Act."],
        ["Accommodation", "Max 10% of gross wage if employer provides accommodation (SD7 S.19)."],
        ["Other Deductions", "No deduction may be made without written consent of the employee."],
    ];
    for (const [label, value] of dedRows) {
        p2.drawText(`${label}:`, { x: MARGIN + 8, y: cy, size: 9, font: bold, color: SLATE });
        p2.drawText(value, { x: MARGIN + 170, y: cy, size: 9, font: regular, color: DARK, maxWidth: BODY_W - 170 });
        cy -= 22;
    }

    cy -= 10;

    // Section 7: Notice Period
    section(p2, "7. NOTICE PERIOD (BCEA S.37)", cy);
    cy -= 30;
    p2.drawText(
        "• ≤ 6 months employed: 1 week notice required from either party.\n" +
        "• > 6 months employed: 4 weeks notice required from either party.\n" +
        "• Notice must be given in writing. Notice may not be given during leave periods.",
        { x: MARGIN + 8, y: cy, size: 9, font: regular, color: DARK, lineHeight: 16, maxWidth: BODY_W - 10 }
    );
    cy -= 55;

    // Section 8: Record Keeping
    section(p2, "8. RECORD KEEPING (BCEA S.31)", cy);
    cy -= 30;
    p2.drawText(
        "The employer must keep a written record of employment particulars for each worker.\n" +
        "Records must be retained for 3 years after termination of employment (BCEA S.31).",
        { x: MARGIN + 8, y: cy, size: 9, font: regular, color: DARK, lineHeight: 16, maxWidth: BODY_W - 10 }
    );
    cy -= 40;

    // Section 9: General
    section(p2, "9. GENERAL CONDITIONS", cy);
    cy -= 30;
    const general = [
        "Both parties agree to treat each other with dignity and respect.",
        "This contract is governed by the laws of the Republic of South Africa.",
        "Any dispute arising from this contract shall first be referred to the CCMA for conciliation.",
        "No variation/amendment of this contract is valid unless agreed to in writing.",
    ];
    for (const clause of general) {
        p2.drawText(`• ${clause}`, { x: MARGIN + 8, y: cy, size: 9, font: regular, color: DARK, maxWidth: BODY_W - 10 });
        cy -= 18;
    }

    cy -= 20;

    // Signatures
    section(p2, "10. SIGNATURES", cy);
    cy -= 50;

    // Employer signature block
    p2.drawLine({ start: { x: MARGIN, y: cy }, end: { x: MARGIN + 180, y: cy }, thickness: 0.5, color: DARK });
    p2.drawText("Employer Signature", { x: MARGIN, y: cy - 14, size: 8, font: bold, color: SLATE });
    p2.drawText(settings.employerName || "Employer", { x: MARGIN, y: cy - 26, size: 8, font: regular, color: DARK });
    p2.drawText(`Date: ____________________`, { x: MARGIN, y: cy - 38, size: 8, font: regular, color: SLATE });

    // Employee signature block
    const rCol = PAGE_W - MARGIN - 180;
    p2.drawLine({ start: { x: rCol, y: cy }, end: { x: rCol + 180, y: cy }, thickness: 0.5, color: DARK });
    p2.drawText("Employee Signature", { x: rCol, y: cy - 14, size: 8, font: bold, color: SLATE });
    p2.drawText(employee.name, { x: rCol, y: cy - 26, size: 8, font: regular, color: DARK });
    p2.drawText(`Date: ____________________`, { x: rCol, y: cy - 38, size: 8, font: regular, color: SLATE });

    // BCEA Compliance Seal
    const sealX = PAGE_W / 2;
    const sealY = 95;
    p2.drawCircle({ x: sealX, y: sealY, size: 28, color: BG_SECTION, borderColor: AMBER, borderWidth: 1.5 });
    p2.drawText("BCEA", { x: sealX - bold.widthOfTextAtSize("BCEA", 7) / 2, y: sealY + 5, size: 7, font: bold, color: AMBER });
    p2.drawText("SD7", { x: sealX - regular.widthOfTextAtSize("SD7", 6) / 2, y: sealY - 5, size: 6, font: regular, color: SLATE });

    return pdfDoc.save();
}
