import { PDFDocument, rgb, type Color, type PDFFont, type PDFPage } from "pdf-lib";
import { format } from "date-fns";
import type { Employee, EmployerSettings, PayslipInput } from "./schema";
import { calculatePayslip, type PayBreakdown } from "./calculator";
import { loadPdfFonts } from "./pdf-fonts";
import { drawPdfBrandMark } from "./pdf-brand";
import { PDF_COLORS as SHARED_PDF_COLORS } from "./pdf-theme";
import { buildPayrollSummary, buildPayrollSummaryFromBreakdown } from "./payroll-summary";

export const PDF_COLORS = {
    ...SHARED_PDF_COLORS,
    PRIMARY_BLUE: rgb(62 / 255, 95 / 255, 104 / 255),
};

export const PDF_MARGIN = 50;
export const PDF_LAYOUT = {
    COL1: 50,
    COL2: 300,
    LINE_HEIGHT: 20,
};

type SupportLang = "en" | "zu" | "xh";

interface PayslipPdfDictionary {
    payslip: string;
    netPayable: string;
    employee: string;
    employer: string;
    payPeriod: string;
    description: string;
    hours: string;
    rate: string;
    total: string;
    grossEarnings: string;
    deductions: string;
    totalDeductions: string;
    uifEmployee: string;
    accommodation: string;
    ordinaryHours: string;
    overtime: string;
    sundayPay: string;
    publicHoliday: string;
    daysWorked: string;
    paymentDate: string;
    employeeId: string;
    occupation: string;
    advanceRecovery: string;
    otherDeductions: string;
    notProvided: string;
    leaveRecorded: string;
    annual: string;
    sick: string;
    family: string;
    grossPayLabel: string;
    employeeUifLabel: string;
    netPayToEmployeeLabel: string;
    employerUifLabel: string;
    totalUifDueLabel: string;
    employerTotalCostLabel: string;
}

export interface PayslipPdfTemplateData {
    headerPeriodLabel: string;
    payPeriodLabel: string;
    daysWorkedLine: string;
    paymentDateLine: string;
    employeeIdLine: string;
    occupationLine: string;
    leaveSummaryLine: string | null;
    footerLine: string;
    netPayLabel: string;
}

type TextRenderer = (
    text: string,
    x: number,
    y: number,
    opts?: {
        font?: PDFFont;
        size?: number;
        color?: Color;
        align?: "left" | "right" | "center";
        maxWidth?: number;
    },
) => void;

type LineRenderer = (
    y: number,
    x1?: number,
    x2?: number,
    thickness?: number,
    color?: Color,
) => void;

interface PdfRenderContext {
    page: PDFPage;
    width: number;
    t: TextRenderer;
}

interface PdfTableContext {
    width: number;
    t: TextRenderer;
    drawLine: LineRenderer;
}

const FOOTER_BRAND_LINE = "Payslip generated by LekkerLedger - Household Payroll Simplified";

const TRANSLATIONS: Record<SupportLang, PayslipPdfDictionary> = {
    en: {
        payslip: "PAYSLIP",
        netPayable: "NET AMOUNT PAID",
        employee: "EMPLOYEE",
        employer: "EMPLOYER",
        payPeriod: "PAY PERIOD",
        description: "DESCRIPTION",
        hours: "HOURS",
        rate: "RATE",
        total: "TOTAL",
        grossEarnings: "GROSS EARNINGS",
        deductions: "DEDUCTIONS",
        totalDeductions: "TOTAL DEDUCTIONS",
        uifEmployee: "UIF (Employee 1%)",
        accommodation: "Accommodation (Capped 10%)",
        ordinaryHours: "Ordinary Hours",
        overtime: "Overtime (1.5x)",
        sundayPay: "Sunday Pay",
        publicHoliday: "Public Holiday (2x)",
        daysWorked: "Days Worked",
        paymentDate: "Payment Date",
        employeeId: "ID / Passport",
        occupation: "Occupation",
        advanceRecovery: "Advance recovered",
        otherDeductions: "Other agreed deductions",
        notProvided: "Not provided",
        leaveRecorded: "Leave taken in this period",
        annual: "Annual",
        sick: "Sick",
        family: "Family",
        grossPayLabel: "Gross pay",
        employeeUifLabel: "Employee UIF deduction",
        netPayToEmployeeLabel: "Net pay to employee",
        employerUifLabel: "Employer UIF contribution",
        totalUifDueLabel: "Total UIF due",
        employerTotalCostLabel: "Employer total cost",
    },
    zu: {
        payslip: "ISILIPHU SEHOLO",
        netPayable: "IMALI EKHOKHIWEYO",
        employee: "UMSEBENZI",
        employer: "UMQASHI",
        payPeriod: "ISIKHATHI SOKUHOLA",
        description: "INCAZELO",
        hours: "AMAHORA",
        rate: "IZINGA",
        total: "INGQIKITHI",
        grossEarnings: "INANI LILONKE",
        deductions: "IZIMALI EZIDONSWAYO",
        totalDeductions: "IZIMALI EZIDONSIWE ZONKE",
        uifEmployee: "I-UIF (Umnikelo woMsebenzi 1%)",
        accommodation: "Indawo yokuhlala (Inqunywe ku-10%)",
        ordinaryHours: "Amahora Ajwayelekile",
        overtime: "Isikhathi Esengeziwe",
        sundayPay: "Inkokhelo YangeSonto",
        publicHoliday: "Iholide Lomphakathi",
        daysWorked: "Izinsuku Ezisetshenziwe",
        paymentDate: "Usuku Lokukhokha",
        employeeId: "I-ID / Ipasipoti",
        occupation: "Umsebenzi",
        advanceRecovery: "Imbuyiselo yenkokhelo yangaphambili",
        otherDeductions: "Ezinye izimali ezidonsiwe okuvunyelwene ngazo",
        notProvided: "Akufakwanga",
        leaveRecorded: "Ikhefu kule nkathi",
        annual: "Lonyaka",
        sick: "Lokugula",
        family: "Lomndeni",
        grossPayLabel: "Inani lilonke",
        employeeUifLabel: "I-UIF yomsebenzi",
        netPayToEmployeeLabel: "Imali yomsebenzi",
        employerUifLabel: "I-UIF yomqashi",
        totalUifDueLabel: "I-UIF yonke",
        employerTotalCostLabel: "Izindleko zomqashi",
    },
    xh: {
        payslip: "ISILIPHU SOMVUZO",
        netPayable: "IMALI EHLAWULIWEYO",
        employee: "UMSEBENZI",
        employer: "UMQASHI",
        payPeriod: "IXESHA LOMVUZO",
        description: "INKCAZELO",
        hours: "IIYURE",
        rate: "IZINGA",
        total: "IMALI IONKE",
        grossEarnings: "IMALI IONKE",
        deductions: "IZITHABATHO",
        totalDeductions: "IZITHABATHO ZONKE",
        uifEmployee: "I-UIF (Igalelo lomsebenzi 1%)",
        accommodation: "Indawo yokuhlala (Ilinganiselwe kwi-10%)",
        ordinaryHours: "Iiyure Eziqhelekileyo",
        overtime: "Ixesha Elingaphezulu",
        sundayPay: "Intlawulo YeCawe",
        publicHoliday: "Iholide Yoluntu",
        daysWorked: "Iintsuku Ezisetyenzisiweyo",
        paymentDate: "Umhla Wentlawulo",
        employeeId: "I-ID / Ipaspoti",
        occupation: "Umsebenzi",
        advanceRecovery: "Imbuyiselo yentlawulo yangaphambili",
        otherDeductions: "Ezinye izithabatho ekuvunyelwene ngazo",
        notProvided: "Ayifakwanga",
        leaveRecorded: "Ikhefu kweli xesha",
        annual: "Yonyaka",
        sick: "Yokugula",
        family: "Yosapho",
        grossPayLabel: "Imali iyonke",
        employeeUifLabel: "I-UIF yomsebenzi",
        netPayToEmployeeLabel: "Imali yomsebenzi",
        employerUifLabel: "I-UIF yomqashi",
        totalUifDueLabel: "I-UIF iyonke",
        employerTotalCostLabel: "Iindleko zomqashi",
    },
};

export function getPayslipFilename(employee: Employee, payslip: PayslipInput): string {
    const monthStr = format(new Date(payslip.payPeriodStart), "yyyy-MM");
    const safeName = employee.name.replaceAll(/[^a-z0-9]/gi, "_");
    const runId = payslip.id.slice(-4);
    return `LekkerLedger_Payslip_${safeName}_${monthStr}_${runId}.pdf`;
}

export function buildPayslipPdfTemplateData(
    employee: Employee,
    payslip: PayslipInput,
    lang: SupportLang = "en",
): PayslipPdfTemplateData {
    return buildPayslipPdfTemplateDataFromBreakdown(
        employee,
        payslip,
        calculatePayslip(payslip),
        lang,
    );
}

function buildPayslipPdfTemplateDataFromBreakdown(
    employee: Employee,
    payslip: PayslipInput,
    breakdown: PayBreakdown,
    lang: SupportLang,
): PayslipPdfTemplateData {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    const periodStart = new Date(payslip.payPeriodStart);
    const periodEnd = new Date(payslip.payPeriodEnd);
    const paymentDate = payslip.createdAt ? new Date(payslip.createdAt) : periodEnd;
    const employeeIdentifier = employee.idNumber?.trim() || dict.notProvided;
    const occupation = employee.role?.trim() || dict.notProvided;
    const leaveSummaryLine = buildLeaveSummaryLine(dict, breakdown);

    return {
        headerPeriodLabel: formatHeaderPeriodLabel(periodStart, periodEnd),
        payPeriodLabel: `${format(periodStart, "dd MMM yyyy")} - ${format(periodEnd, "dd MMM yyyy")}`,
        daysWorkedLine: `${dict.daysWorked}: ${formatDayCount(payslip.daysWorked)}`,
        paymentDateLine: `${dict.paymentDate}: ${format(paymentDate, "dd MMM yyyy")}`,
        employeeIdLine: `${dict.employeeId}: ${employeeIdentifier}`,
        occupationLine: `${dict.occupation}: ${occupation}`,
        leaveSummaryLine,
        footerLine: FOOTER_BRAND_LINE,
        netPayLabel: dict.netPayable,
    };
}

function buildLeaveSummaryLine(
    dict: PayslipPdfDictionary,
    breakdown: PayBreakdown,
): string | null {
    const leaveItems = [
        breakdown.leaveTaken.annual > 0 ? `${dict.annual}: ${formatDayCount(breakdown.leaveTaken.annual)}` : null,
        breakdown.leaveTaken.sick > 0 ? `${dict.sick}: ${formatDayCount(breakdown.leaveTaken.sick)}` : null,
        breakdown.leaveTaken.family > 0 ? `${dict.family}: ${formatDayCount(breakdown.leaveTaken.family)}` : null,
    ].filter((value): value is string => Boolean(value));

    return leaveItems.length > 0 ? `${dict.leaveRecorded}: ${leaveItems.join(" | ")}` : null;
}

function formatHeaderPeriodLabel(periodStart: Date, periodEnd: Date): string {
    const sameMonth = format(periodStart, "yyyy-MM") === format(periodEnd, "yyyy-MM");
    if (sameMonth) {
        return format(periodEnd, "MMMM yyyy").toUpperCase();
    }

    const sameYear = format(periodStart, "yyyy") === format(periodEnd, "yyyy");
    if (sameYear) {
        return `${format(periodStart, "MMM")} - ${format(periodEnd, "MMM yyyy")}`.toUpperCase();
    }

    return `${format(periodStart, "MMM yyyy")} - ${format(periodEnd, "MMM yyyy")}`.toUpperCase();
}

function formatDayCount(value: number): string {
    const safeValue = Number.isFinite(value) ? value : 0;
    const numericText = Number.isInteger(safeValue)
        ? String(safeValue)
        : safeValue.toFixed(2).replace(/\.?0+$/, "");

    return `${numericText} ${Math.abs(safeValue) === 1 ? "day" : "days"}`;
}

export async function generatePayslipPdfBytes(
    employee: Employee,
    payslip: PayslipInput,
    settings: EmployerSettings,
    lang: SupportLang = "en",
): Promise<Uint8Array> {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    const breakdown = calculatePayslip(payslip);
    const payrollSummary = buildPayrollSummaryFromBreakdown(breakdown);
    const templateData = buildPayslipPdfTemplateDataFromBreakdown(employee, payslip, breakdown, lang);

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]);
    const { width, height } = page.getSize();
    const { sansRegular, sansBold, serifBold } = await loadPdfFonts(pdfDoc);

    const t: TextRenderer = (
        text: string,
        x: number,
        y: number,
        opts,
    ) => {
        const font = opts?.font ?? sansRegular;
        const size = opts?.size ?? 9;
        const color = opts?.color ?? PDF_COLORS.TEXT;
        let displayTxt = String(text ?? "");

        if (Number.isNaN(x) || Number.isNaN(y)) return;

        if (opts?.maxWidth && font.widthOfTextAtSize(displayTxt, size) > opts.maxWidth) {
            const ellipsis = "...";
            while (
                displayTxt.length > 0
                && font.widthOfTextAtSize(`${displayTxt}${ellipsis}`, size) > opts.maxWidth
            ) {
                displayTxt = displayTxt.slice(0, -1);
            }
            displayTxt += ellipsis;
        }

        let tx = x;
        const textWidth = font.widthOfTextAtSize(displayTxt, size);
        if (opts?.align === "right") {
            tx = x - textWidth;
        } else if (opts?.align === "center") {
            tx = x - (textWidth / 2);
        }

        page.drawText(displayTxt, { x: tx, y, size, font, color });
    };

    const drawLine: LineRenderer = (
        y: number,
        x1 = PDF_MARGIN,
        x2 = width - PDF_MARGIN,
        thickness = 0.5,
        color = PDF_COLORS.BORDER,
    ) => {
        page.drawLine({ start: { x: x1, y }, end: { x: x2, y }, thickness, color });
    };

    page.drawRectangle({ x: 0, y: 0, width, height, color: PDF_COLORS.PAPER });

    const renderContext: PdfRenderContext = { page, width, t };
    const tableContext: PdfTableContext = { width, t, drawLine };
    const headerY = drawHeader(page, width, dict, templateData, serifBold, sansBold, t);
    let cy = drawParties(renderContext, headerY, {
        dict,
        employee,
        settings,
        templateData,
        sansBold,
        sansRegular,
    });
    cy = drawEarningsTable(tableContext, cy, {
        dict,
        payslip,
        breakdown,
        sansBold,
        sansRegular,
    });
    cy = drawDeductionsTable(tableContext, cy, {
        dict,
        payslip,
        breakdown,
        sansBold,
    });
    drawNetPaySummary(renderContext, cy, {
        dict,
        templateData,
        payrollSummary,
        serifBold,
        sansBold,
        sansRegular,
    });
    drawFooter(page, width, templateData, sansRegular, t, drawLine);

    return pdfDoc.save({ useObjectStreams: false });
}

function drawHeader(
    page: PDFPage,
    width: number,
    dict: PayslipPdfDictionary,
    templateData: PayslipPdfTemplateData,
    serifBold: PDFFont,
    sansBold: PDFFont,
    t: (
        text: string,
        x: number,
        y: number,
        opts?: {
            font?: PDFFont;
            size?: number;
            color?: Color;
            align?: "left" | "right" | "center";
            maxWidth?: number;
        },
    ) => void,
): number {
    const height = page.getSize().height;
    const headerY = height - 60;

    drawPdfBrandMark(page, { x: PDF_MARGIN, y: headerY - 22, size: 30 });
    t(dict.payslip, width - PDF_MARGIN, headerY, { font: serifBold, size: 15, align: "right" });
    t(templateData.headerPeriodLabel, width - PDF_MARGIN, headerY - 13, {
        font: sansBold,
        size: 8.5,
        color: PDF_COLORS.TEXT_MUTED,
        align: "right",
    });

    page.drawLine({
        start: { x: PDF_MARGIN, y: headerY - 28 },
        end: { x: width - PDF_MARGIN, y: headerY - 28 },
        thickness: 1,
        color: PDF_COLORS.BORDER,
    });

    return headerY;
}

function drawParties(
    renderContext: PdfRenderContext,
    headerY: number,
    data: {
        dict: PayslipPdfDictionary;
        employee: Employee;
        settings: EmployerSettings;
        templateData: PayslipPdfTemplateData;
        sansBold: PDFFont;
        sansRegular: PDFFont;
    },
): number {
    const { page, width, t } = renderContext;
    const { dict, employee, settings, templateData, sansBold, sansRegular } = data;
    const cy = headerY - 60;
    const infoBottomY = templateData.leaveSummaryLine ? cy - 78 : cy - 64;
    const employerX = PDF_MARGIN;
    const employeeX = PDF_MARGIN + 220;
    const periodX = width - PDF_MARGIN;

    t(dict.employer, employerX, cy - 2, { font: sansBold, size: 7, color: PDF_COLORS.TEXT_MUTED });
    t(settings.employerName || dict.notProvided, employerX, cy - 18, { font: sansBold, size: 10, maxWidth: 180 });
    if (settings.employerAddress?.trim()) {
        t(settings.employerAddress, employerX, cy - 31, {
            font: sansRegular,
            size: 7.5,
            color: PDF_COLORS.TEXT_MUTED,
            maxWidth: 180,
        });
    }
    t(templateData.paymentDateLine, employerX, cy - 44, {
        font: sansRegular,
        size: 7.5,
        color: PDF_COLORS.TEXT_MUTED,
        maxWidth: 180,
    });

    t(dict.employee, employeeX, cy - 2, { font: sansBold, size: 7, color: PDF_COLORS.TEXT_MUTED });
    t(employee.name || dict.notProvided, employeeX, cy - 18, { font: sansBold, size: 10, maxWidth: 150 });
    if (employee.role?.trim()) {
        t(employee.role, employeeX, cy - 31, {
            font: sansRegular,
            size: 8,
            color: PDF_COLORS.TEXT_MUTED,
            maxWidth: 150,
        });
    }
    t(templateData.employeeIdLine, employeeX, cy - 44, {
        font: sansRegular,
        size: 7.5,
        color: PDF_COLORS.TEXT_MUTED,
        maxWidth: 150,
    });

    t(dict.payPeriod, periodX, cy - 2, {
        font: sansBold,
        size: 7,
        color: PDF_COLORS.TEXT_MUTED,
        align: "right",
    });
    t(templateData.payPeriodLabel, periodX, cy - 18, {
        font: sansRegular,
        size: 9,
        align: "right",
        maxWidth: 180,
    });
    t(templateData.daysWorkedLine, periodX, cy - 31, {
        font: sansRegular,
        size: 8,
        color: PDF_COLORS.TEXT_MUTED,
        align: "right",
        maxWidth: 180,
    });
    t(templateData.occupationLine, periodX, cy - 44, {
        font: sansRegular,
        size: 7.5,
        color: PDF_COLORS.TEXT_MUTED,
        align: "right",
        maxWidth: 180,
    });
    if (templateData.leaveSummaryLine) {
        t(templateData.leaveSummaryLine, periodX, cy - 57, {
            font: sansRegular,
            size: 7,
            color: PDF_COLORS.TEXT_MUTED,
            align: "right",
            maxWidth: 200,
        });
    }

    page.drawLine({
        start: { x: PDF_MARGIN, y: infoBottomY },
        end: { x: width - PDF_MARGIN, y: infoBottomY },
        thickness: 0.5,
        color: PDF_COLORS.BORDER,
    });

    return infoBottomY;
}

function drawEarningsTable(
    tableContext: PdfTableContext,
    startY: number,
    data: {
        dict: PayslipPdfDictionary;
        payslip: PayslipInput;
        breakdown: PayBreakdown;
        sansBold: PDFFont;
        sansRegular: PDFFont;
    },
): number {
    const { width, t, drawLine } = tableContext;
    const { dict, payslip, breakdown, sansBold, sansRegular } = data;
    let cy = startY - 22;
    t(dict.description, PDF_MARGIN, cy, { font: sansBold, size: 8, color: PDF_COLORS.TEXT_MUTED });
    t(dict.hours, width - 150, cy, { font: sansBold, size: 8, color: PDF_COLORS.TEXT_MUTED, align: "right" });
    t(dict.rate, width - 100, cy, { font: sansBold, size: 8, color: PDF_COLORS.TEXT_MUTED, align: "right" });
    t(dict.total, width - PDF_MARGIN, cy, { font: sansBold, size: 8, color: PDF_COLORS.TEXT_MUTED, align: "right" });

    drawLine(cy - 6);
    cy -= 20;

    const renderRow = (label: string, hours: string, rate: string, total: string, isBold = false) => {
        t(label, PDF_MARGIN, cy, { font: isBold ? sansBold : sansRegular, size: 9 });
        t(hours, width - 150, cy, { font: sansRegular, size: 9, align: "right" });
        t(rate, width - 100, cy, { font: sansRegular, size: 9, align: "right" });
        t(total, width - PDF_MARGIN, cy, { font: sansBold, size: 9, align: "right" });
        cy -= 18;
    };

    renderRow(
        dict.ordinaryHours,
        breakdown.effectiveOrdinaryHours.toString(),
        `R ${breakdown.hourlyRate.toFixed(2)}`,
        `R ${breakdown.ordinaryPay.toFixed(2)}`,
    );

    if (payslip.overtimeHours > 0) {
        renderRow(
            dict.overtime,
            payslip.overtimeHours.toString(),
            `R ${(breakdown.hourlyRate * 1.5).toFixed(2)}`,
            `R ${breakdown.overtimePay.toFixed(2)}`,
        );
    }
    if (payslip.sundayHours > 0) {
        const multiplier = payslip.ordinarilyWorksSundays ? 1.5 : 2.0;
        renderRow(
            `${dict.sundayPay} (${multiplier}x)`,
            payslip.sundayHours.toString(),
            `R ${(breakdown.hourlyRate * multiplier).toFixed(2)}`,
            `R ${breakdown.sundayPay.toFixed(2)}`,
        );
    }
    if (payslip.publicHolidayHours > 0) {
        renderRow(
            dict.publicHoliday,
            payslip.publicHolidayHours.toString(),
            `R ${(breakdown.hourlyRate * 2).toFixed(2)}`,
            `R ${breakdown.publicHolidayPay.toFixed(2)}`,
        );
    }

    drawLine(cy + 5);
    cy -= 15;
    t(dict.grossEarnings, PDF_MARGIN, cy, { font: sansBold, size: 10 });
    t(`R ${breakdown.grossPay.toFixed(2)}`, width - PDF_MARGIN, cy, {
        font: sansBold,
        size: 11,
        align: "right",
    });

    return cy;
}

function drawDeductionsTable(
    tableContext: PdfTableContext,
    startY: number,
    data: {
        dict: PayslipPdfDictionary;
        payslip: PayslipInput;
        breakdown: PayBreakdown;
        sansBold: PDFFont;
    },
): number {
    const { width, t, drawLine } = tableContext;
    const { dict, payslip, breakdown, sansBold } = data;
    let cy = startY - 35;
    t(dict.deductions, PDF_MARGIN, cy, { font: sansBold, size: 8, color: PDF_COLORS.TEXT_MUTED });
    drawLine(cy - 6);
    cy -= 20;

    const renderDeductionRow = (label: string, amount: number) => {
        t(label, PDF_MARGIN, cy, { size: 9, color: PDF_COLORS.TEXT_MUTED });
        t(`- R ${amount.toFixed(2)}`, width - PDF_MARGIN, cy, {
            size: 9,
            align: "right",
            color: PDF_COLORS.DANGER,
        });
        cy -= 18;
    };

    if (breakdown.deductions.uifEmployee > 0) {
        renderDeductionRow(dict.uifEmployee, breakdown.deductions.uifEmployee);
    }
    if (payslip.includeAccommodation && breakdown.deductions.accommodation) {
        renderDeductionRow(dict.accommodation, breakdown.deductions.accommodation);
    }
    if ((payslip.advanceAmount ?? 0) > 0) {
        renderDeductionRow(dict.advanceRecovery, payslip.advanceAmount ?? 0);
    }
    if ((payslip.otherDeductions ?? 0) > 0) {
        renderDeductionRow(dict.otherDeductions, payslip.otherDeductions ?? 0);
    }

    drawLine(cy + 5);
    cy -= 15;
    t(dict.totalDeductions, PDF_MARGIN, cy, { font: sansBold, size: 9, color: PDF_COLORS.TEXT_MUTED });
    t(`R ${breakdown.deductions.total.toFixed(2)}`, width - PDF_MARGIN, cy, {
        font: sansBold,
        size: 9,
        align: "right",
    });

    return cy;
}

function drawNetPaySummary(
    renderContext: PdfRenderContext,
    startY: number,
    data: {
        dict: PayslipPdfDictionary;
        templateData: PayslipPdfTemplateData;
        payrollSummary: ReturnType<typeof buildPayrollSummary>;
        serifBold: PDFFont;
        sansBold: PDFFont;
        sansRegular: PDFFont;
    },
) {
    const { page, width, t } = renderContext;
    const { dict, templateData, payrollSummary, serifBold, sansBold, sansRegular } = data;
    const boxY = startY - 40;
    const netPayHeight = 106;

    page.drawRectangle({
        x: PDF_MARGIN,
        y: boxY,
        width: width - (PDF_MARGIN * 2),
        height: netPayHeight,
        color: PDF_COLORS.SURFACE,
        borderColor: PDF_COLORS.BORDER,
        borderWidth: 0.8,
    });
    page.drawLine({
        start: { x: PDF_MARGIN, y: boxY },
        end: { x: width - PDF_MARGIN, y: boxY },
        thickness: 1.1,
        color: PDF_COLORS.PRIMARY_GREEN,
    });

    const rows = [
        { label: dict.grossPayLabel, value: payrollSummary.grossPay, bold: false },
        { label: dict.employeeUifLabel, value: payrollSummary.employeeUifDeduction, bold: false },
        { label: dict.netPayToEmployeeLabel || templateData.netPayLabel, value: payrollSummary.netPayToEmployee, bold: true },
        { label: dict.employerUifLabel, value: payrollSummary.employerUifContribution, bold: false },
        { label: dict.totalUifDueLabel, value: payrollSummary.totalUifDue, bold: false },
        { label: dict.employerTotalCostLabel, value: payrollSummary.employerTotalCost, bold: true },
    ];

    let currentY = boxY + netPayHeight - 16;
    for (const row of rows) {
        t(row.label, PDF_MARGIN + 14, currentY, {
            font: row.bold ? sansBold : sansRegular,
            size: 8.5,
            color: PDF_COLORS.TEXT,
        });
        t(`R ${row.value.toFixed(2)}`, width - PDF_MARGIN - 14, currentY, {
            font: row.bold ? serifBold : sansBold,
            size: row.bold ? 10.5 : 9,
            color: PDF_COLORS.TEXT,
            align: "right",
        });
        currentY -= 15;
    }
}

function drawFooter(
    page: PDFPage,
    width: number,
    templateData: PayslipPdfTemplateData,
    sansRegular: PDFFont,
    t: (
        text: string,
        x: number,
        y: number,
        opts?: {
            font?: PDFFont;
            size?: number;
            color?: Color;
            align?: "left" | "right" | "center";
            maxWidth?: number;
        },
    ) => void,
    drawLine: (
        y: number,
        x1?: number,
        x2?: number,
        thickness?: number,
        color?: Color,
    ) => void,
) {
    drawLine(52);
    t(templateData.footerLine, width / 2, 30, {
        font: sansRegular,
        size: 7,
        color: PDF_COLORS.TEXT_MUTED,
        align: "center",
    });
}
