/**
 * Share utility — WhatsApp sharing for payslip PDFs
 * Uses Web Share API on mobile, wa.me fallback on desktop
 */

export async function shareViaWhatsApp(
    pdfBytes: Uint8Array,
    employeeName: string,
    phone: string,
    periodLabel: string
): Promise<boolean> {
    const fileName = `Payslip_${employeeName.replace(/\s+/g, "_")}_${periodLabel}.pdf`;
    const file = new File([pdfBytes.slice(0)], fileName, { type: "application/pdf" });

    // Try Web Share API first (works on mobile browsers)
    if (navigator.share && navigator.canShare?.({ files: [file] })) {
        try {
            await navigator.share({
                title: `Payslip for ${employeeName}`,
                text: `Hi ${employeeName.split(" ")[0]}, here is your payslip for ${periodLabel}. Generated by LekkerLedger.`,
                files: [file],
            });
            return true;
        } catch (err) {
            // User cancelled or share failed — fall through to wa.me
            if ((err as Error).name === "AbortError") return false;
        }
    }

    // Fallback: open wa.me with pre-filled text
    const cleanPhone = phone.replace(/\D/g, "");
    const intlPhone = cleanPhone.startsWith("0") ? "27" + cleanPhone.slice(1) : cleanPhone;
    const message = encodeURIComponent(
        `Hi ${employeeName.split(" ")[0]}, here is your payslip for ${periodLabel}. Generated by LekkerLedger.`
    );
    window.open(`https://wa.me/${intlPhone}?text=${message}`, "_blank");

    // Also trigger PDF download so user can attach it manually
    downloadPdf(pdfBytes, fileName);
    return true;
}

export function downloadPdf(pdfBytes: Uint8Array, fileName: string): void {
    const blob = new Blob([pdfBytes.slice(0)], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
}
