import { PDFDocument, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { format } from "date-fns";
import { calculatePayslip } from "./calculator";
import { drawPdfBrandLockup } from "./pdf-brand";
import { loadPdfFonts } from "./pdf-fonts";
import type { Employee, LeaveRecord, PayPeriod, PayslipInput } from "./schema";

const PAGE_SIZE: [number, number] = [595.28, 841.89];
const MARGIN = 48;
const LINE_HEIGHT = 16;

interface YearEndSummaryOptions {
    year: number;
    householdName?: string;
    employees: Employee[];
    payslips: PayslipInput[];
    leaveRecords: LeaveRecord[];
    payPeriods: PayPeriod[];
    generatedAt?: Date;
}

interface EmployeeSummaryRow {
    employee: Employee;
    monthsWorked: number;
    ordinaryPay: number;
    overtimePay: number;
    sundayPay: number;
    deductions: number;
    netPay: number;
    annualLeave: number;
    sickLeave: number;
    familyLeave: number;
}

function uniqueMonthKey(date: Date): string {
    return `${date.getFullYear()}-${date.getMonth()}`;
}

function createPage(
    pdfDoc: PDFDocument,
    fonts: { sansRegular: PDFFont; sansBold: PDFFont; serifBold: PDFFont },
    options: YearEndSummaryOptions,
    pageNumber: number,
) {
    const page = pdfDoc.addPage(PAGE_SIZE);
    const { width, height } = page.getSize();
    drawPdfBrandLockup(page, {
        x: MARGIN,
        y: height - 52,
        size: 23,
        serifBold: fonts.serifBold,
        sansBold: fonts.sansBold,
        subtitle: "YEAR-END SUMMARY",
        titleSize: 16,
    });

    const title = `${options.householdName?.trim() || "Employment Summary"} - ${options.year}`;
    page.drawText(title, {
        x: MARGIN,
        y: height - 88,
        size: 15,
        font: fonts.serifBold,
        color: rgb(16 / 255, 24 / 255, 40 / 255),
    });

    page.drawText(`Generated ${format(options.generatedAt || new Date(), "d MMM yyyy")}`, {
        x: width - MARGIN - fonts.sansRegular.widthOfTextAtSize(`Generated ${format(options.generatedAt || new Date(), "d MMM yyyy")}`, 8),
        y: height - 88,
        size: 8,
        font: fonts.sansRegular,
        color: rgb(71 / 255, 84 / 255, 103 / 255),
    });

    page.drawLine({
        start: { x: MARGIN, y: height - 98 },
        end: { x: width - MARGIN, y: height - 98 },
        thickness: 1,
        color: rgb(230 / 255, 224 / 255, 214 / 255),
    });

    page.drawText(`Page ${pageNumber}`, {
        x: width - MARGIN - fonts.sansRegular.widthOfTextAtSize(`Page ${pageNumber}`, 8),
        y: 26,
        size: 8,
        font: fonts.sansRegular,
        color: rgb(71 / 255, 84 / 255, 103 / 255),
    });

    const footer = `Generated by LekkerLedger on ${format(options.generatedAt || new Date(), "d MMM yyyy")}. This is a summary of records you entered. It is not a tax document and has not been independently verified.`;
    page.drawText(footer, {
        x: MARGIN,
        y: 26,
        size: 7,
        font: fonts.sansRegular,
        color: rgb(71 / 255, 84 / 255, 103 / 255),
        maxWidth: width - (MARGIN * 2) - 48,
    });

    return page;
}

function matchesLockedPeriod(payslip: PayslipInput, lockedPeriods: PayPeriod[]) {
    return lockedPeriods.some((period) =>
        period.status === "locked"
        && period.startDate === format(new Date(payslip.payPeriodStart), "yyyy-MM-dd")
        && period.endDate === format(new Date(payslip.payPeriodEnd), "yyyy-MM-dd"),
    );
}

export function getYearEndSummaryStatus(payPeriods: PayPeriod[], year: number) {
    const periodsForYear = payPeriods.filter((period) => new Date(period.endDate).getFullYear() === year);
    return {
        availableYears: Array.from(new Set(payPeriods.map((period) => new Date(period.endDate).getFullYear()))).sort((a, b) => b - a),
        unlockedMonthCount: periodsForYear.filter((period) => period.status !== "locked").length,
    };
}

export async function generateYearEndSummaryPdf(options: YearEndSummaryOptions): Promise<Uint8Array> {
    const generatedAt = options.generatedAt || new Date();
    const lockedPeriods = options.payPeriods.filter((period) => period.status === "locked" && new Date(period.endDate).getFullYear() === options.year);
    const payslips = options.payslips.filter((payslip) => new Date(payslip.payPeriodEnd).getFullYear() === options.year && matchesLockedPeriod(payslip, lockedPeriods));

    const employeeRows: EmployeeSummaryRow[] = options.employees.map((employee) => {
        const employeePayslips = payslips.filter((payslip) => payslip.employeeId === employee.id);
        const leaveRecords = options.leaveRecords.filter((record) => {
            const leaveDate = new Date(record.endDate || record.startDate || record.date);
            return record.employeeId === employee.id && leaveDate.getFullYear() === options.year;
        });
        const monthKeys = new Set<string>();

        let ordinaryPay = 0;
        let overtimePay = 0;
        let sundayPay = 0;
        let deductions = 0;
        let netPay = 0;

        for (const payslip of employeePayslips) {
            const breakdown = calculatePayslip(payslip);
            ordinaryPay += breakdown.ordinaryPay;
            overtimePay += breakdown.overtimePay;
            sundayPay += breakdown.sundayPay + breakdown.publicHolidayPay;
            deductions += breakdown.deductions.total;
            netPay += breakdown.netPay;
            monthKeys.add(uniqueMonthKey(new Date(payslip.payPeriodEnd)));
        }

        return {
            employee,
            monthsWorked: monthKeys.size,
            ordinaryPay,
            overtimePay,
            sundayPay,
            deductions,
            netPay,
            annualLeave: leaveRecords.filter((record) => record.type === "annual").reduce((sum, record) => sum + record.days, 0),
            sickLeave: leaveRecords.filter((record) => record.type === "sick").reduce((sum, record) => sum + record.days, 0),
            familyLeave: leaveRecords.filter((record) => record.type === "family").reduce((sum, record) => sum + record.days, 0),
        };
    }).filter((row) => row.monthsWorked > 0 || row.netPay > 0 || row.annualLeave > 0 || row.sickLeave > 0 || row.familyLeave > 0);

    const totals = employeeRows.reduce((acc, row) => ({
        ordinaryPay: acc.ordinaryPay + row.ordinaryPay,
        overtimePay: acc.overtimePay + row.overtimePay,
        sundayPay: acc.sundayPay + row.sundayPay,
        deductions: acc.deductions + row.deductions,
        netPay: acc.netPay + row.netPay,
    }), {
        ordinaryPay: 0,
        overtimePay: 0,
        sundayPay: 0,
        deductions: 0,
        netPay: 0,
    });

    const pdfDoc = await PDFDocument.create();
    const fonts = await loadPdfFonts(pdfDoc);
    let page = createPage(pdfDoc, fonts, { ...options, generatedAt }, 1);
    let pageNumber = 1;
    let y = PAGE_SIZE[1] - 122;

    const drawText = (targetPage: PDFPage, text: string, x: number, drawY: number, font: PDFFont, size = 9, color = rgb(16 / 255, 24 / 255, 40 / 255)) => {
        targetPage.drawText(text, { x, y: drawY, font, size, color });
    };

    const ensureSpace = (needed: number) => {
        if (y - needed >= 52) return;
        pageNumber += 1;
        page = createPage(pdfDoc, fonts, { ...options, generatedAt }, pageNumber);
        y = PAGE_SIZE[1] - 122;
    };

    drawText(page, "Employee", MARGIN, y, fonts.sansBold, 9, rgb(71 / 255, 84 / 255, 103 / 255));
    drawText(page, "Months", 230, y, fonts.sansBold, 9, rgb(71 / 255, 84 / 255, 103 / 255));
    drawText(page, "Ordinary", 285, y, fonts.sansBold, 9, rgb(71 / 255, 84 / 255, 103 / 255));
    drawText(page, "Overtime", 360, y, fonts.sansBold, 9, rgb(71 / 255, 84 / 255, 103 / 255));
    drawText(page, "Sundays", 435, y, fonts.sansBold, 9, rgb(71 / 255, 84 / 255, 103 / 255));
    drawText(page, "Net", 510, y, fonts.sansBold, 9, rgb(71 / 255, 84 / 255, 103 / 255));
    y -= 14;

    for (const row of employeeRows) {
        ensureSpace(48);
        page.drawLine({
            start: { x: MARGIN, y: y + 6 },
            end: { x: PAGE_SIZE[0] - MARGIN, y: y + 6 },
            thickness: 0.5,
            color: rgb(230 / 255, 224 / 255, 214 / 255),
        });
        drawText(page, row.employee.name, MARGIN, y - 2, fonts.sansBold, 9);
        drawText(page, row.employee.role, MARGIN, y - 14, fonts.sansRegular, 8, rgb(71 / 255, 84 / 255, 103 / 255));
        drawText(page, String(row.monthsWorked), 240, y - 2, fonts.sansRegular, 9);
        drawText(page, `R ${row.ordinaryPay.toFixed(2)}`, 285, y - 2, fonts.sansRegular, 9);
        drawText(page, `R ${row.overtimePay.toFixed(2)}`, 360, y - 2, fonts.sansRegular, 9);
        drawText(page, `R ${row.sundayPay.toFixed(2)}`, 435, y - 2, fonts.sansRegular, 9);
        drawText(page, `R ${row.netPay.toFixed(2)}`, 510, y - 2, fonts.sansBold, 9);
        drawText(page, `Leave: annual ${row.annualLeave}d, sick ${row.sickLeave}d, family ${row.familyLeave}d`, 240, y - 16, fonts.sansRegular, 8, rgb(71 / 255, 84 / 255, 103 / 255));
        y -= 34;
    }

    ensureSpace(70);
    page.drawRectangle({
        x: MARGIN,
        y: y - 18,
        width: PAGE_SIZE[0] - (MARGIN * 2),
        height: 56,
        borderColor: rgb(230 / 255, 224 / 255, 214 / 255),
        borderWidth: 0.8,
        color: rgb(250 / 255, 247 / 255, 240 / 255),
    });
    drawText(page, "Grand totals", MARGIN + 12, y + 20, fonts.serifBold, 11);
    drawText(page, `Ordinary: R ${totals.ordinaryPay.toFixed(2)}`, MARGIN + 12, y + 5, fonts.sansRegular, 9);
    drawText(page, `Overtime: R ${totals.overtimePay.toFixed(2)}`, MARGIN + 12, y - 10, fonts.sansRegular, 9);
    drawText(page, `Sundays/Public Holidays: R ${totals.sundayPay.toFixed(2)}`, 240, y + 5, fonts.sansRegular, 9);
    drawText(page, `Deductions: R ${totals.deductions.toFixed(2)}`, 240, y - 10, fonts.sansRegular, 9);
    drawText(page, `Net paid: R ${totals.netPay.toFixed(2)}`, 430, y + 5, fonts.sansBold, 10);

    return pdfDoc.save();
}
