import type { Metadata } from "next";
import Link from "next/link";
import { AlertCircle, RefreshCw, FileText, ArrowRight } from "lucide-react";
import { MarketingHeader } from "@/components/layout/marketing-header";
import { Button } from "@/components/ui/button";
import { ComplianceDisclaimer } from "@/components/seo/compliance-disclaimer";
import { JsonLd } from "@/components/seo/json-ld";
import { pageOG } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Solve uFiling Errors: Employee Not Declared & Upload Issues | LekkerLedger",
  description: "Struggling with the uFiling portal? Learn how to bypass common errors by uploading a perfectly formatted CSV declaration generated by LekkerLedger.",
  alternates: {
    canonical: "/ufiling-errors",
  },
  ...pageOG(
    "Solve uFiling Errors: Employee Not Declared & Upload Issues | LekkerLedger",
    "Struggling with the uFiling portal? Learn how to bypass common errors by uploading a perfectly formatted CSV declaration generated by LekkerLedger.",
    "/ufiling-errors",
  ),
};

const ufilingHowToSchema = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to bypass uFiling errors with CSV uploads",
  description: "Stop fighting manual uFiling entry. Upload a pre-formatted CSV generated by LekkerLedger instead.",
  step: [
    {
      "@type": "HowToStep",
      position: 1,
      name: "Generate your monthly payslip",
      text: "Generate your monthly payslip in LekkerLedger as usual.",
    },
    {
      "@type": "HowToStep",
      position: 2,
      name: "Download the uFiling export",
      text: "At the end of the month, download the uFiling export from your Standard or Pro dashboard.",
    },
    {
      "@type": "HowToStep",
      position: 3,
      name: "Upload the CSV to uFiling",
      text: "Log into uFiling, go to Returns, select Upload File, and select the CSV you just downloaded.",
    },
    {
      "@type": "HowToStep",
      position: 4,
      name: "Done",
      text: "The system instantly accepts the perfectly formatted data without timeouts or manual entry errors.",
    },
  ],
};

export default function UFilingErrorsPage() {
    return (
        <div className="min-h-screen flex flex-col" style={{ backgroundColor: "var(--bg)" }}>
            <JsonLd schema={ufilingHowToSchema} />
            <MarketingHeader />

            <main className="flex-1">
                {/* HERO SECTION */}
                <section className="px-4 py-16 sm:py-24 content-container-wide bg-[var(--surface-1)] border-b border-[var(--border)]">
                    <div className="max-w-4xl mx-auto text-center space-y-8">
                        <div className="mx-auto h-16 w-16 rounded-2xl bg-red-500/10 flex items-center justify-center mb-6">
                            <AlertCircle className="h-8 w-8 text-red-500" />
                        </div>
                        <h1 className="type-h1 max-w-3xl mx-auto" style={{ color: "var(--text)" }}>
                            Common uFiling Errors (And How to Bypass Them)
                        </h1>
                        <p className="text-xl leading-relaxed max-w-2xl mx-auto" style={{ color: "var(--text-muted)" }}>
                            The official uFiling portal is notorious for timeouts, &quot;Employee not declared&quot; errors, and manual entry failures. Stop typing manually and switch to CSV uploads.
                        </p>
                    </div>
                </section>

                <section className="px-4 py-16 content-container sm:py-24">
                    <div className="max-w-3xl mx-auto space-y-12">

                        <div className="space-y-6">
                            <h2 className="type-h2" style={{ color: "var(--text)" }}>The problem with manual entry</h2>
                            <p className="text-base leading-relaxed" style={{ color: "var(--text-muted)" }}>
                                Most household employers log into uFiling and attempt to manually capture their domestic worker&apos;s hours and salary on the &quot;Declarations&quot; screen. This method frequently results in the following frustations:
                            </p>
                            
                            <div className="grid sm:grid-cols-2 gap-4 mt-6">
                                <div className="p-6 rounded-2xl border border-[var(--border)] bg-[var(--surface-raised)]">
                                    <h3 className="font-bold text-red-500 mb-2">Error 404 / 500</h3>
                                    <p className="text-sm" style={{ color: "var(--text-muted)" }}>The session times out before you finish typing, forcing you to start over.</p>
                                </div>
                                <div className="p-6 rounded-2xl border border-[var(--border)] bg-[var(--surface-raised)]">
                                    <h3 className="font-bold text-amber-500 mb-2">&quot;Employee Missing&quot;</h3>
                                    <p className="text-sm" style={{ color: "var(--text-muted)" }}>You manually type the ID number, but the system says they are not registered to your profile.</p>
                                </div>
                                <div className="p-6 rounded-2xl border border-[var(--border)] bg-[var(--surface-raised)]">
                                    <h3 className="font-bold text-orange-500 mb-2">Decimal Formatting</h3>
                                    <p className="text-sm" style={{ color: "var(--text-muted)" }}>Entering a comma instead of a dot (or vice versa) triggers an invalid amount error.</p>
                                </div>
                                <div className="p-6 rounded-2xl border border-[var(--border)] bg-[var(--surface-raised)]">
                                    <h3 className="font-bold text-blue-500 mb-2">Slow Loading</h3>
                                    <p className="text-sm" style={{ color: "var(--text-muted)" }}>Clicking through four different screens just to declare one employee takes too long.</p>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-6">
                            <h2 className="type-h2" style={{ color: "var(--text)" }}>The Recommended Solution: CSV Uploads</h2>
                            <p className="text-base leading-relaxed" style={{ color: "var(--text-muted)" }}>
                                Experienced payroll administrators <b>never</b> use the manual entry screens. They use the &quot;Upload Payroll File&quot; feature. This allows you to upload a simple spreadsheet (CSV mapped to exactly what uFiling expects), bypassing the slow manual forms entirely.
                            </p>
                            
                            <div className="rounded-2xl bg-emerald-500/5 border border-emerald-500/20 p-8 mt-6">
                                <h3 className="font-bold text-lg mb-4 flex items-center gap-2" style={{ color: "var(--text)" }}>
                                    <RefreshCw className="h-5 w-5 text-emerald-500" />
                                    The LekkerLedger Workflow
                                </h3>
                                <ul className="space-y-4">
                                    <li className="flex items-start gap-3">
                                        <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-700">1</div>
                                        <p className="text-sm">You generate your monthly payslip in LekkerLedger as usual.</p>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-700">2</div>
                                        <p className="text-sm">At the end of the month, download <b>&quot;uFiling Export&quot;</b> from your Standard or Pro dashboard.</p>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-700">3</div>
                                        <p className="text-sm">Log into uFiling, go to Returns, select Upload File, and select the CSV you just downloaded.</p>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[var(--primary)] text-xs font-bold text-white">4</div>
                                        <p className="text-sm font-bold text-[var(--test)]">Done. The system instantly accepts the perfectly formatted data without timeouts.</p>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div className="bg-[var(--surface-raised)] border border-[var(--border)] rounded-2xl p-8 text-center space-y-6">
                            <FileText className="h-10 w-10 text-[var(--text-muted)] mx-auto" />
                            <h3 className="text-xl font-bold" style={{ color: "var(--text)" }}>Ready to stop fighting uFiling?</h3>
                            <p className="text-sm max-w-xl mx-auto" style={{ color: "var(--text-muted)" }}>
                                The uFiling CSV export is available on Standard and Pro paid plans. Compare the paid tiers to choose the one that matches your household.
                            </p>
                            <Link href="/pricing" className="inline-block">
                                <Button size="lg" className="h-12 px-8 bg-[var(--primary)] hover:bg-[var(--primary-hover)] text-white rounded-full">
                                    See plans with uFiling CSV export
                                </Button>
                            </Link>
                        </div>

                        {/* Related Resources */}
                        <div className="space-y-4">
                            <h2 className="type-h3 font-semibold" style={{ color: "var(--text)" }}>Related Resources</h2>
                            <div className="grid sm:grid-cols-2 gap-3">
                                {[
                                    { href: "/resources/guides/uif-for-domestic-workers", label: "UIF for Domestic Workers Guide" },
                                    { href: "/resources/tools/domestic-worker-payslip", label: "Free Payslip Generator" },
                                    { href: "/uif-calculator", label: "UIF Calculator" },
                                    { href: "/resources/checklists/household-employer-monthly", label: "Monthly Compliance Checklist" },
                                ].map((link) => (
                                    <Link key={link.href} href={link.href} className="flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface-raised)] p-4 text-sm font-medium transition-colors hover:border-[var(--primary)]/40" style={{ color: "var(--text)" }}>
                                        <ArrowRight className="h-4 w-4 shrink-0 text-[var(--primary)]" />
                                        {link.label}
                                    </Link>
                                ))}
                            </div>
                        </div>

                        <ComplianceDisclaimer />

                    </div>
                </section>
            </main>
        </div>
    );
}
