import { AUDIT_IDS } from "./helpers";
import type { AuditAction, AuditDevice, AuditGroup, SeedMode } from "./types";

function createVisitActions(
    group: AuditGroup,
    device: AuditDevice,
    seed: SeedMode,
    prefix: string,
    defs: Array<[string, string, string]>,
): AuditAction[] {
    return defs.map(([idSuffix, route, label]) => ({
        id: `${prefix}-${idSuffix}-${device}`,
        group,
        label,
        route,
        device,
        seed,
    }));
}

const marketingActions: AuditAction[] = [
    ...createVisitActions("marketing", "mobile", "empty", "marketing", [
        ["home", "/", "Open homepage on phone"],
        ["pricing", "/pricing", "Open pricing page on phone"],
        ["calculator", "/calculator", "Open calculator page on phone"],
        ["rules", "/rules", "Open rules page on phone"],
        ["trust", "/trust", "Open trust page on phone"],
        ["support", "/support", "Open support page on phone"],
        ["storage", "/storage", "Open storage page on phone"],
        ["examples", "/examples", "Open examples page on phone"],
        ["privacy", "/legal/privacy", "Open privacy page on phone"],
        ["terms", "/legal/terms", "Open terms page on phone"],
        ["refunds", "/legal/refunds", "Open refunds page on phone"],
        ["open-app", "/open-app", "Open app handoff page on phone"],
        ["privacy-policy", "/legal/privacy", "Re-open privacy page on phone"],
        ["terms-alias", "/legal/terms-of-service", "Open terms alias on phone"],
    ]),
    ...createVisitActions("marketing", "desktop", "empty", "marketing", [
        ["home", "/", "Open homepage on desktop"],
        ["pricing", "/pricing", "Open pricing page on desktop"],
        ["calculator", "/calculator", "Open calculator page on desktop"],
        ["trust", "/trust", "Open trust page on desktop"],
        ["support", "/support", "Open support page on desktop"],
        ["storage", "/storage", "Open storage page on desktop"],
        ["examples", "/examples", "Open examples page on desktop"],
        ["privacy", "/legal/privacy", "Open privacy page on desktop"],
        ["terms", "/legal/terms", "Open terms page on desktop"],
        ["refunds", "/legal/refunds", "Open refunds page on desktop"],
    ]),
    {
        id: "marketing-home-menu-open-mobile",
        group: "marketing",
        label: "Open the homepage mobile menu",
        route: "/",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickByRole", role: "button", name: "Open menu" },
            { type: "assertText", text: "How it works" },
        ],
    },
    {
        id: "marketing-home-menu-close-mobile",
        group: "marketing",
        label: "Close the homepage mobile menu",
        route: "/",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickByRole", role: "button", name: "Open menu" },
            { type: "press", key: "Escape" },
        ],
    },
    {
        id: "marketing-home-start-free-mobile",
        group: "marketing",
        label: "Follow the homepage Email yourself a payslip PDF CTA on phone",
        route: "/",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickByRole", role: "link", name: "Email yourself a payslip PDF (free—1/month)" },
            { type: "waitForUrl", pattern: "/resources/tools/domestic-worker-payslip" },
        ],
    },
    {
        id: "marketing-home-pricing-cta-mobile",
        group: "marketing",
        label: "Follow the homepage pricing CTA on phone",
        route: "/",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickByRole", role: "link", name: "See full pricing" },
            { type: "waitForUrl", pattern: "/pricing" },
        ],
    },
    {
        id: "marketing-home-storage-cta-mobile",
        group: "marketing",
        label: "Open the homepage device-change FAQ on phone",
        route: "/",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickSelector", selector: "section#faq details:nth-of-type(5) summary" },
            { type: "assertText", text: "Paid accounts store everything in the cloud." },
        ],
    },
    {
        id: "marketing-pricing-toggle-monthly-mobile",
        group: "marketing",
        label: "Switch pricing to monthly on phone",
        route: "/pricing",
        device: "mobile",
        seed: "empty",
        steps: [{ type: "clickByRole", role: "button", name: "Monthly" }],
    },
    {
        id: "marketing-pricing-toggle-yearly-mobile",
        group: "marketing",
        label: "Switch pricing to yearly on phone",
        route: "/pricing",
        device: "mobile",
        seed: "empty",
        steps: [{ type: "clickByRole", role: "button", name: "Yearly" }],
    },
    {
        id: "marketing-home-faq-open-mobile",
        group: "marketing",
        label: "Open a homepage FAQ item on phone",
        route: "/",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickSelector", selector: "section#faq details:nth-of-type(3) summary" },
            { type: "assertText", text: "Paid accounts store records in end-to-end encrypted cloud storage" },
        ],
    },
];

const onboardingShellActions: AuditAction[] = [
    ...createVisitActions("onboarding-shell", "mobile", "starter", "shell", [
        ["onboarding", "/onboarding", "Open onboarding on phone"],
        ["dashboard", "/dashboard", "Open dashboard on phone"],
        ["settings", "/settings", "Open settings on phone"],
        ["settings-storage", "/settings?tab=storage", "Open storage settings on phone"],
        ["settings-plan", "/settings?tab=plan", "Open billing settings on phone"],
        ["settings-exports", "/settings?tab=exports", "Open exports settings on phone"],
        ["settings-support", "/settings?tab=support", "Open support settings on phone"],
    ]),
    ...createVisitActions("onboarding-shell", "desktop", "starter", "shell", [
        ["onboarding", "/onboarding", "Open onboarding on desktop"],
        ["dashboard", "/dashboard", "Open dashboard on desktop"],
        ["settings", "/settings", "Open settings on desktop"],
        ["settings-storage", "/settings?tab=storage", "Open storage settings on desktop"],
        ["settings-plan", "/settings?tab=plan", "Open billing settings on desktop"],
        ["settings-exports", "/settings?tab=exports", "Open exports settings on desktop"],
        ["settings-support", "/settings?tab=support", "Open support settings on desktop"],
    ]),
    {
        id: "shell-onboarding-start-free-mobile",
        group: "onboarding-shell",
        label: "Start free from onboarding on phone",
        route: "/onboarding",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickByRole", role: "link", name: "Start free" },
            { type: "waitForUrl", pattern: "/dashboard" },
        ],
    },
    {
        id: "shell-onboarding-view-plans-mobile",
        group: "onboarding-shell",
        label: "Open pricing from onboarding on phone",
        route: "/onboarding",
        device: "mobile",
        seed: "empty",
        steps: [
            { type: "clickByRole", role: "link", name: "View plans" },
            { type: "waitForUrl", pattern: "/pricing" },
        ],
    },
    {
        id: "shell-onboarding-note-mobile",
        group: "onboarding-shell",
        label: "Review the onboarding local-first note on phone",
        route: "/onboarding",
        device: "mobile",
        seed: "empty",
        steps: [{ type: "assertText", text: "The free payslip tool works in the browser and does not keep records after the session." }],
    },
    {
        id: "shell-dashboard-open-account-desktop",
        group: "onboarding-shell",
        label: "Open the desktop account menu",
        route: "/dashboard",
        device: "desktop",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "account-menu-toggle" }],
    },
    {
        id: "shell-bottom-nav-home-mobile",
        group: "onboarding-shell",
        label: "Confirm the Home tab is visible on phone",
        route: "/payroll",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "assertText", text: "Home" }],
    },
    {
        id: "shell-bottom-nav-payroll-mobile",
        group: "onboarding-shell",
        label: "Use bottom nav Payroll on phone",
        route: "/dashboard",
        device: "mobile",
        seed: "starter",
        steps: [
            { type: "clickTestId", testId: "bottom-nav-payroll" },
            { type: "waitForUrl", pattern: "/payroll" },
        ],
    },
    {
        id: "shell-bottom-nav-employees-mobile",
        group: "onboarding-shell",
        label: "Use bottom nav Employees on phone",
        route: "/dashboard",
        device: "mobile",
        seed: "starter",
        steps: [
            { type: "clickTestId", testId: "bottom-nav-employees" },
            { type: "waitForUrl", pattern: "/employees" },
        ],
    },
    {
        id: "shell-bottom-nav-documents-mobile",
        group: "onboarding-shell",
        label: "Use bottom nav Documents on phone",
        route: "/employees",
        device: "mobile",
        seed: "starter",
        steps: [
            { type: "clickTestId", testId: "bottom-nav-docs" },
            { type: "waitForUrl", pattern: "/documents" },
        ],
    },
    {
        id: "shell-bottom-nav-more-mobile",
        group: "onboarding-shell",
        label: "Use bottom nav More on phone",
        route: "/dashboard",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "bottom-nav-more" }],
    },
    {
        id: "shell-settings-tab-general-mobile",
        group: "onboarding-shell",
        label: "Open the General settings tab on phone",
        route: "/settings",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "settings-tab-general" }],
    },
    {
        id: "shell-settings-tab-storage-mobile",
        group: "onboarding-shell",
        label: "Open the Storage settings tab on phone",
        route: "/settings",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "settings-tab-storage" }],
    },
    {
        id: "shell-settings-tab-plan-mobile",
        group: "onboarding-shell",
        label: "Open the Billing settings tab on phone",
        route: "/settings",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "settings-tab-plan" }],
    },
    {
        id: "shell-settings-tab-exports-mobile",
        group: "onboarding-shell",
        label: "Open the Exports settings tab on phone",
        route: "/settings",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "settings-tab-exports" }],
    },
    {
        id: "shell-settings-tab-support-mobile",
        group: "onboarding-shell",
        label: "Open the Help settings tab on phone",
        route: "/settings",
        device: "mobile",
        seed: "starter",
        steps: [{ type: "clickTestId", testId: "settings-tab-support" }],
    },
];

const employeeActions: AuditAction[] = [
    ...createVisitActions("employees-leave-contracts", "mobile", "full", "employees", [
        ["list", "/employees", "Open employees list on phone"],
        ["new", "/employees/new", "Open new employee page on phone"],
        ["detail-a", `/employees/${AUDIT_IDS.employeeA}`, "Open employee A detail on phone"],
        ["detail-b", `/employees/${AUDIT_IDS.employeeB}`, "Open employee B detail on phone"],
        ["edit-a", `/employees/${AUDIT_IDS.employeeA}/edit`, "Open employee edit page on phone"],
        ["history-a", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee history on phone"],
        ["leave", "/leave", "Open leave page on phone"],
        ["leave-new", "/leave/new", "Open new leave page on phone"],
        ["contracts", "/documents?tab=contracts", "Open contracts page on phone"],
        ["contracts-new", "/contracts/new", "Open new contract page on phone"],
        ["employees-again", "/employees", "Re-open employees list on phone"],
        ["contracts-again", "/documents?tab=contracts", "Re-open contracts page on phone"],
    ]),
    ...createVisitActions("employees-leave-contracts", "desktop", "full", "employees", [
        ["list", "/employees", "Open employees list on desktop"],
        ["new", "/employees/new", "Open new employee page on desktop"],
        ["detail-a", `/employees/${AUDIT_IDS.employeeA}`, "Open employee A detail on desktop"],
        ["detail-b", `/employees/${AUDIT_IDS.employeeB}`, "Open employee B detail on desktop"],
        ["edit-a", `/employees/${AUDIT_IDS.employeeA}/edit`, "Open employee edit page on desktop"],
        ["history-a", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee history on desktop"],
        ["leave", "/leave", "Open leave page on desktop"],
        ["leave-new", "/leave/new", "Open new leave page on desktop"],
        ["contracts", "/documents?tab=contracts", "Open contracts page on desktop"],
        ["contracts-new", "/contracts/new", "Open new contract page on desktop"],
        ["employees-search", "/employees", "Re-open employees list for search on desktop"],
        ["contracts-again", "/documents?tab=contracts", "Re-open contracts page on desktop"],
    ]),
    {
        id: "employees-search-thandi-desktop",
        group: "employees-leave-contracts",
        label: "Confirm Thandi appears in the employee list on desktop",
        route: "/employees",
        device: "desktop",
        seed: "full",
        steps: [{ type: "assertText", text: "Thandi Dlamini" }],
    },
    {
        id: "employees-search-sipho-desktop",
        group: "employees-leave-contracts",
        label: "Confirm Sipho appears in the employee list on desktop",
        route: "/employees",
        device: "desktop",
        seed: "full",
        steps: [{ type: "assertText", text: "Sipho Maseko" }],
    },
    {
        id: "employees-create-form-mobile",
        group: "employees-leave-contracts",
        label: "Fill key employee fields on the new employee form on phone",
        route: "/employees/new",
        device: "mobile",
        seed: "starter",
        steps: [
            { type: "fill", selector: "#name", value: "Audit Worker" },
            { type: "fill", selector: "#role", value: "Housekeeper" },
            { type: "fill", selector: "#hourlyRate", value: "31" },
        ],
    },
    {
        id: "employees-create-form-desktop",
        group: "employees-leave-contracts",
        label: "Fill key employee fields on the new employee form on desktop",
        route: "/employees/new",
        device: "desktop",
        seed: "starter",
        steps: [
            { type: "fill", selector: "#name", value: "Audit Worker" },
            { type: "fill", selector: "#role", value: "Housekeeper" },
            { type: "fill", selector: "#hourlyRate", value: "31" },
        ],
    },
    {
        id: "employees-open-detail-from-list-desktop",
        group: "employees-leave-contracts",
        label: "Open an employee from the table on desktop",
        route: "/employees",
        device: "desktop",
        seed: "full",
        steps: [
            { type: "clickSelector", selector: `a[href='/employees/${AUDIT_IDS.employeeA}']` },
            { type: "waitForUrl", pattern: `/employees/${AUDIT_IDS.employeeA}` },
        ],
    },
    {
        id: "employees-open-detail-from-list-mobile",
        group: "employees-leave-contracts",
        label: "Open an employee from the list on phone",
        route: "/employees",
        device: "mobile",
        seed: "full",
        steps: [{ type: "assertText", text: "Thandi Dlamini" }],
    },
    {
        id: "employees-open-leave-route-desktop",
        group: "employees-leave-contracts",
        label: "Open leave records again on desktop",
        route: "/leave",
        device: "desktop",
        seed: "full",
    },
];

const payrollActions: AuditAction[] = [
    ...createVisitActions("payroll-documents-history", "tablet", "full", "payroll", [
        ["list", "/payroll", "Open payroll list on tablet"],
        ["draft", `/payroll/${AUDIT_IDS.draftPeriodId}`, "Open draft pay period on tablet"],
        ["preview", `/preview?payslipId=${AUDIT_IDS.payslipA}&empId=${AUDIT_IDS.employeeA}`, "Open payslip preview on tablet"],
        ["documents", "/documents", "Open documents hub on tablet"],
        ["history", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee pay history on tablet"],
    ]),
    ...createVisitActions("payroll-documents-history", "mobile", "full", "payroll", [
        ["list", "/payroll", "Open payroll list on phone"],
        ["new", "/payroll/new", "Open new payroll wizard on phone"],
        ["draft", `/payroll/${AUDIT_IDS.draftPeriodId}`, "Open draft pay period on phone"],
        ["locked", `/payroll/${AUDIT_IDS.lockedPeriodId}`, "Open locked pay period on phone"],
        ["wizard", `/wizard?empId=${AUDIT_IDS.employeeA}`, "Open payslip wizard on phone"],
        ["preview", `/preview?payslipId=${AUDIT_IDS.payslipA}&empId=${AUDIT_IDS.employeeA}`, "Open payslip preview on phone"],
        ["documents", "/documents", "Open documents hub on phone"],
        ["history", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee pay history on phone"],
        ["employee-history", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee history from payroll context on phone"],
        ["documents-again", "/documents", "Re-open documents hub on phone"],
        ["preview-again", "/preview", "Re-open preview page on phone"],
        ["payroll-again", "/payroll", "Re-open payroll list on phone"],
        ["draft-again", `/payroll/${AUDIT_IDS.draftPeriodId}`, "Re-open draft pay period on phone"],
    ]),
    ...createVisitActions("payroll-documents-history", "desktop", "full", "payroll", [
        ["list", "/payroll", "Open payroll list on desktop"],
        ["new", "/payroll/new", "Open new payroll wizard on desktop"],
        ["draft", `/payroll/${AUDIT_IDS.draftPeriodId}`, "Open draft pay period on desktop"],
        ["locked", `/payroll/${AUDIT_IDS.lockedPeriodId}`, "Open locked pay period on desktop"],
        ["wizard", `/wizard?empId=${AUDIT_IDS.employeeA}`, "Open payslip wizard on desktop"],
        ["preview", `/preview?payslipId=${AUDIT_IDS.payslipA}&empId=${AUDIT_IDS.employeeA}`, "Open payslip preview on desktop"],
        ["documents", "/documents", "Open documents hub on desktop"],
        ["history", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee pay history on desktop"],
        ["employee-history", `/employees/${AUDIT_IDS.employeeA}/history`, "Open employee history from payroll context on desktop"],
        ["documents-again", "/documents", "Re-open documents hub on desktop"],
        ["preview-again", "/preview", "Re-open preview page on desktop"],
        ["payroll-again", "/payroll", "Re-open payroll list on desktop"],
        ["draft-again", `/payroll/${AUDIT_IDS.draftPeriodId}`, "Re-open draft pay period on desktop"],
    ]),
    {
        id: "payroll-wizard-start-mobile",
        group: "payroll-documents-history",
        label: "Review the new payroll wizard employee step on phone",
        route: "/payroll/new",
        device: "mobile",
        seed: "full",
        steps: [{ type: "assertText", text: "Who are you paying?" }],
    },
    {
        id: "payroll-wizard-select-employee-mobile",
        group: "payroll-documents-history",
        label: "Review employee choices in the new payroll wizard on phone",
        route: "/payroll/new",
        device: "mobile",
        seed: "full",
        steps: [
            { type: "assertText", text: "Who are you paying?" },
            { type: "assertText", text: "Thandi Dlamini" },
        ],
    },
    {
        id: "payroll-wizard-next-to-dates-mobile",
        group: "payroll-documents-history",
        label: "Advance the new payroll wizard to dates on phone",
        route: "/payroll/new",
        device: "mobile",
        seed: "full",
        steps: [
            { type: "clickTestId", testId: "payroll-wizard-next-to-dates" },
            { type: "assertText", text: "Set the pay period" },
        ],
    },
    {
        id: "payroll-wizard-set-dates-mobile",
        group: "payroll-documents-history",
        label: "Edit pay period dates in the wizard on phone",
        route: "/payroll/new",
        device: "mobile",
        seed: "full",
        steps: [
            { type: "clickTestId", testId: "payroll-wizard-next-to-dates" },
            { type: "assertText", text: "Set the pay period" },
            { type: "fill", selector: "[data-testid='payroll-wizard-start-date']", value: "2026-04-01" },
            { type: "fill", selector: "[data-testid='payroll-wizard-end-date']", value: "2026-04-30" },
        ],
    },
    {
        id: "payroll-wizard-start-desktop",
        group: "payroll-documents-history",
        label: "Review the new payroll wizard employee step on desktop",
        route: "/payroll/new",
        device: "desktop",
        seed: "full",
        steps: [{ type: "assertText", text: "Who are you paying?" }],
    },
    {
        id: "payroll-wizard-initialize-desktop",
        group: "payroll-documents-history",
        label: "Initialize a new pay run on desktop",
        route: "/payroll/new",
        device: "desktop",
        seed: "full",
        steps: [
            { type: "clickTestId", testId: "payroll-wizard-next-to-dates" },
            { type: "assertText", text: "Set the pay period" },
            { type: "clickTestId", testId: "payroll-wizard-initialize" },
            { type: "waitForUrl", pattern: "/payroll/" },
        ],
    },
    {
        id: "payroll-open-current-period-desktop",
        group: "payroll-documents-history",
        label: "Open the current payroll period from the list on desktop",
        route: "/payroll",
        device: "desktop",
        seed: "full",
        steps: [
            { type: "clickSelector", selector: `a[href='/payroll/${AUDIT_IDS.draftPeriodId}']` },
            { type: "waitForUrl", pattern: `/payroll/${AUDIT_IDS.draftPeriodId}` },
        ],
    },
    {
        id: "payroll-documents-view-desktop",
        group: "payroll-documents-history",
        label: "Inspect document actions on desktop",
        route: "/documents",
        device: "desktop",
        seed: "full",
    },
    {
        id: "payroll-documents-view-mobile",
        group: "payroll-documents-history",
        label: "Inspect document actions on phone",
        route: "/documents",
        device: "mobile",
        seed: "full",
    },
    {
        id: "payroll-preview-download-surface-desktop",
        group: "payroll-documents-history",
        label: "Inspect the preview download surface on desktop",
        route: `/preview?payslipId=${AUDIT_IDS.payslipA}&empId=${AUDIT_IDS.employeeA}`,
        device: "desktop",
        seed: "full",
    },
];

const complianceActions: AuditAction[] = [
    ...createVisitActions("compliance-storage-billing", "mobile", "full", "compliance", [
        ["ufiling", "/ufiling", "Open uFiling page on phone"],
        ["roe", "/compliance/coida/roe", "Open COIDA ROE page on phone"],
        ["help-compliance", "/help/compliance", "Open compliance help on phone"],
        ["help-coida", "/help/coida", "Open COIDA help on phone"],
        ["upgrade", "/upgrade", "Open upgrade page on phone"],
        ["billing-success", "/billing/success", "Open billing success page on phone"],
        ["billing-cancel", "/billing/cancel", "Open billing cancel page on phone"],
        ["settings-storage", "/settings?tab=storage", "Open storage settings on phone for sync review"],
        ["settings-exports", "/settings?tab=exports", "Open exports settings on phone for backup review"],
        ["settings-support", "/settings?tab=support", "Open support settings on phone for help review"],
        ["open-app", "/open-app", "Open app handoff on phone for billing/compliance context"],
        ["support", "/support", "Open support page on phone for contact checks"],
        ["trust", "/trust", "Open trust page on phone for privacy checks"],
        ["pricing", "/pricing", "Re-open pricing page on phone for billing comparison"],
    ]),
    ...createVisitActions("compliance-storage-billing", "desktop", "full", "compliance", [
        ["ufiling", "/ufiling", "Open uFiling page on desktop"],
        ["roe", "/compliance/coida/roe", "Open COIDA ROE page on desktop"],
        ["help-compliance", "/help/compliance", "Open compliance help on desktop"],
        ["help-coida", "/help/coida", "Open COIDA help on desktop"],
        ["upgrade", "/upgrade", "Open upgrade page on desktop"],
        ["billing-success", "/billing/success", "Open billing success page on desktop"],
        ["billing-cancel", "/billing/cancel", "Open billing cancel page on desktop"],
        ["settings-storage", "/settings?tab=storage", "Open storage settings on desktop for sync review"],
        ["settings-exports", "/settings?tab=exports", "Open exports settings on desktop for backup review"],
        ["settings-support", "/settings?tab=support", "Open support settings on desktop for help review"],
        ["support", "/support", "Open support page on desktop for contact checks"],
        ["trust", "/trust", "Open trust page on desktop for privacy checks"],
        ["pricing", "/pricing", "Re-open pricing page on desktop for billing comparison"],
        ["storage", "/storage", "Open storage explainer on desktop"],
    ]),
];

export const AUDIT_ACTIONS: AuditAction[] = [
    ...marketingActions,
    ...onboardingShellActions,
    ...employeeActions,
    ...payrollActions,
    ...complianceActions,
];

if (AUDIT_ACTIONS.length < 150) {
    throw new Error(`Audit manifest must contain at least 150 actions. Current count: ${AUDIT_ACTIONS.length}`);
}
