import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { Employee, EmployerSettings } from "./schema";
import { format } from "date-fns";

const AMBER = rgb(0.77, 0.48, 0.11);
const DARK = rgb(0.11, 0.09, 0.08);
const SLATE = rgb(0.45, 0.40, 0.35);
const WHITE = rgb(1, 1, 1);
const LINE = rgb(0.88, 0.86, 0.83);

export async function generateCertificateOfService(
    employee: Employee,
    settings: EmployerSettings
): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_W = 595.28;
    const PAGE_H = 841.89;
    const MARGIN = 50;

    const page = pdfDoc.addPage([PAGE_W, PAGE_H]);
    let cy = PAGE_H - 100;

    // Header block
    page.drawRectangle({ x: 0, y: PAGE_H - 120, width: PAGE_W, height: 120, color: DARK });
    page.drawRectangle({ x: 0, y: PAGE_H - 124, width: PAGE_W, height: 4, color: AMBER });

    page.drawText("CERTIFICATE OF SERVICE", {
        x: PAGE_W / 2 - bold.widthOfTextAtSize("CERTIFICATE OF SERVICE", 24) / 2,
        y: PAGE_H - 60,
        size: 24,
        font: bold,
        color: WHITE,
    });

    page.drawText("(Section 42 of the Basic Conditions of Employment Act)", {
        x: PAGE_W / 2 - regular.widthOfTextAtSize("(Section 42 of the Basic Conditions of Employment Act)", 10) / 2,
        y: PAGE_H - 85,
        size: 10,
        font: regular,
        color: rgb(0.6, 0.55, 0.5),
    });

    // Sections
    function section(title: string, y: number) {
        page.drawText(title.toUpperCase(), { x: MARGIN, y, size: 10, font: bold, color: AMBER });
        page.drawLine({ start: { x: MARGIN, y: y - 5 }, end: { x: PAGE_W - MARGIN, y: y - 5 }, thickness: 0.5, color: LINE });
    }

    function row(label: string, value: string, y: number) {
        page.drawText(label + ":", { x: MARGIN, y, size: 10, font: bold, color: SLATE });
        page.drawText(value || "(Not set)", { x: MARGIN + 140, y, size: 10, font: regular, color: DARK });
    }

    // Employer
    cy = PAGE_H - 180;
    section("1. Employer Details", cy);
    cy -= 25;
    row("Employer Name", settings.employerName, cy);
    cy -= 18;
    row("Address", settings.employerAddress, cy);
    cy -= 18;
    row("UIF Ref Number", settings.uifRefNumber, cy);

    // Employee
    cy -= 45;
    section("2. Employee Details", cy);
    cy -= 25;
    row("Full Name", employee.name, cy);
    cy -= 18;
    row("ID / Passport", employee.idNumber, cy);
    cy -= 18;
    row("Job Title / Role", employee.role, cy);

    // Context
    cy -= 45;
    section("3. Period of Service", cy);
    cy -= 25;
    row("Commencement", employee.startDate ? format(new Date(employee.startDate), "d MMMM yyyy") : "Not set", cy);
    cy -= 18;
    row("Termination", format(new Date(), "d MMMM yyyy"), cy);
    cy -= 18;
    row("Final Rate", `R ${employee.hourlyRate.toFixed(2)} per hour`, cy);

    // Duties
    cy -= 40;
    page.drawText("Description of Work Performed:", { x: MARGIN, y: cy, size: 10, font: bold, color: DARK });
    cy -= 18;
    const text = `The employee was employed as a ${employee.role}. All duties per the employment agreement were performed to satisfaction.`;
    page.drawText(text, { x: MARGIN, y: cy, size: 10, font: regular, color: DARK, maxWidth: PAGE_W - MARGIN * 2 });

    // Signatures
    cy = 150;
    page.drawLine({ start: { x: MARGIN, y: cy }, end: { x: MARGIN + 150, y: cy }, thickness: 0.5, color: DARK });
    page.drawText("Employer Signature", { x: MARGIN, y: cy - 12, size: 8, font: regular, color: SLATE });

    page.drawLine({ start: { x: PAGE_W - MARGIN - 150, y: cy }, end: { x: PAGE_W - MARGIN, y: cy }, thickness: 0.5, color: DARK });
    page.drawText("Employee Signature", { x: PAGE_W - MARGIN - 150, y: cy - 12, size: 8, font: regular, color: SLATE });

    // Footer
    page.drawText("Generated by LekkerLedger", { x: PAGE_W / 2 - regular.widthOfTextAtSize("Generated by LekkerLedger", 7) / 2, y: 30, size: 7, font: regular, color: SLATE });

    return pdfDoc.save();
}
