import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { Employee, PayslipInput, EmployerSettings } from "./schema";
import { calculatePayslip } from "./calculator";
import { format } from "date-fns";

const AMBER = rgb(0.77, 0.48, 0.11);
const DARK = rgb(0.11, 0.09, 0.08);
const SLATE = rgb(0.45, 0.40, 0.35);
const WHITE = rgb(1, 1, 1);
const LINE = rgb(0.88, 0.86, 0.83);

/**
 * Generates a Certificate of Service (BCEA Section 42)
 */
export async function generateCertificateOfServicePdf(
    employee: Employee,
    employer: EmployerSettings
): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]);
    const { width, height } = page.getSize();

    const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const t = (text: string, x: number, y: number, size = 10, font = regular, color = DARK) => {
        page.drawText(text, { x, y, size, font, color });
    };

    // Header
    page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: DARK });
    t("CERTIFICATE OF SERVICE", 48, height - 45, 20, bold, WHITE);
    t("In accordance with Section 42 of the Basic Conditions of Employment Act", 48, height - 62, 8, regular, rgb(0.7, 0.7, 0.7));

    let cy = height - 120;

    // Employer Info
    t("EMPLOYER DETAILS", 48, cy, 8, bold, AMBER);
    cy -= 20;
    t(`Name: ${employer.employerName || "N/A"}`, 48, cy);
    cy -= 15;
    t(`Address: ${employer.employerAddress || "N/A"}`, 48, cy);

    cy -= 40;

    // Employee Info
    t("EMPLOYEE DETAILS", 48, cy, 8, bold, AMBER);
    cy -= 20;
    t(`Full Name: ${employee.name}`, 48, cy);
    cy -= 15;
    t(`Identity Number: ${employee.idNumber || "N/A"}`, 48, cy);
    cy -= 15;
    t(`Position: ${employee.role || "Worker"}`, 48, cy);

    cy -= 40;

    // Service Period
    t("PERIOD OF SERVICE", 48, cy, 8, bold, AMBER);
    cy -= 20;
    t(`Date of Commencement: ${employee.startDate ? format(new Date(employee.startDate), "dd MMMM yyyy") : "N/A"}`, 48, cy);
    cy -= 15;
    t(`Date of Termination: ${format(new Date(), "dd MMMM yyyy")} (Date of Issue)`, 48, cy);

    cy -= 40;

    // Job Description
    t("DESCRIPTION OF WORK", 48, cy, 8, bold, AMBER);
    cy -= 20;
    const desc = "The employee was engaged in domestic work and related services, including but not limited to general household management, cleaning, and maintenance in accordance with Sectoral Determination 7.";
    page.drawText(desc, { x: 48, y: cy, size: 10, font: regular, color: DARK, maxWidth: width - 96, lineHeight: 14 });

    cy -= 60;

    // Remuneration
    t("REMUNERATION AT TERMINATION", 48, cy, 8, bold, AMBER);
    cy -= 20;
    t(`Hourly Rate: R${employee.hourlyRate.toFixed(2)}`, 48, cy);
    cy -= 15;
    t(`Pay Frequency: ${employee.frequency || "Monthly"}`, 48, cy);

    cy -= 80;

    // Signatures
    page.drawLine({ start: { x: 48, y: cy }, end: { x: 200, y: cy }, thickness: 1, color: DARK });
    t("Employer Signature", 48, cy - 15, 8, regular, SLATE);

    page.drawLine({ start: { x: width - 200, y: cy }, end: { x: width - 48, y: cy }, thickness: 1, color: DARK });
    t("Date of Issue", width - 200, cy - 15, 8, regular, SLATE);

    // Footer
    t("Generated by LekkerLedger.app - Compliant with BCEA, COIDA & UIF (2026 Rulings)", 48, 40, 7, regular, SLATE);

    return pdfDoc.save();
}

/**
 * Generates a BCEA Section 33 Summary / Audit PDF
 */
export async function generateBCEASummaryPdf(
    employee: Employee,
    payslip: PayslipInput,
    employer: EmployerSettings
): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]);
    const { width, height } = page.getSize();
    const breakdown = calculatePayslip(payslip);

    const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const t = (text: string, x: number, y: number, size = 10, font = regular, color = DARK) => {
        page.drawText(text, { x, y, size, font, color });
    };

    // Header
    page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: rgb(0.1, 0.3, 0.4) });
    t("BCEA COMPLIANCE SUMMARY", 48, height - 42, 18, bold, WHITE);
    t(`Audit for ${employee.name} - Period Ending ${format(payslip.payPeriodEnd, "dd MMM yyyy")}`, 48, height - 60, 9, regular, rgb(0.8, 0.9, 1));

    let cy = height - 120;

    t("Section 33 of the Basic Conditions of Employment Act requires specific information to be provided to employees.", 48, cy, 8, regular, SLATE);
    cy -= 30;

    // Table rows
    const rows = [
        ["Legal Parameter", "Status", "Details"],
        ["National Minimum Wage", breakdown.complianceWarnings.length === 0 ? "Compliant" : "WARNING", `R${employee.hourlyRate.toFixed(2)}/hr`],
        ["UIF Contributions", breakdown.deductions.uifEmployee > 0 ? "Applied" : "Exempt", `R${breakdown.deductions.uifEmployee.toFixed(2)} deducted`],
        ["Accommodation Cap", (breakdown.deductions.accommodation ?? 0) <= breakdown.grossPay * 0.1 ? "Compliant" : "Exceeded", "Max 10% allowed"],
        ["Sunday Pay Rate", employee.ordinarilyWorksSundays ? "1.5x" : "2.0x", "Statutory requirement met"],
        ["Overtime Rate", "1.5x", "Based on SD7 Regulation"],
        ["Leave Accrual", "Active", `${breakdown.leaveAccruedDays} days accrued this period`]
    ];

    rows.forEach((row, i) => {
        const isHeader = i === 0;
        const font = isHeader ? bold : regular;
        const color = isHeader ? AMBER : DARK;

        t(row[0], 48, cy, 9, font, color);
        t(row[1], 200, cy, 9, font, color);
        t(row[2], 300, cy, 9, font, color);

        page.drawLine({ start: { x: 48, y: cy - 5 }, end: { x: width - 48, y: cy - 5 }, thickness: 0.5, color: LINE });
        cy -= 25;
    });

    cy -= 20;
    t("LEAVE RECORD FOR THIS PERIOD", 48, cy, 10, bold, AMBER);
    cy -= 20;
    t(`Annual Leave Taken: ${breakdown.leaveTaken.annual} days`, 48, cy);
    t(`Sick Leave Taken: ${breakdown.leaveTaken.sick} days`, 250, cy);
    cy -= 15;
    t(`Family Responsibility Leave: ${breakdown.leaveTaken.family} days`, 48, cy);

    cy -= 20;
    const decl = "This document confirms that the associated payslip has been calculated according to the regulations set forth in Sectoral Determination 7 for Domestic Workers, COIDA 2026, and UIF requirements in South Africa. The employer confirms the accuracy of the hours and deductions recorded.";
    page.drawText(decl, { x: 48, y: cy, size: 9, font: regular, color: DARK, maxWidth: width - 96, lineHeight: 12 });

    // Footer
    t("Generated by LekkerLedger.app - BCEA, COIDA & UIF Compliance Engine", 48, 40, 7, regular, SLATE);

    return pdfDoc.save();
}
