import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Payslip Example | LekkerLedger",
    description:
        "See a sample domestic worker payslip generated by LekkerLedger. Download a realistic example PDF with UIF deductions and NMW-compliant wages.",
    alternates: { canonical: "/examples" },
};

export default function ExamplesLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return children;
}
